[window]
opacity = 0.7
dynamic_padding = true
decorations = "none"
startup_mode = "Windowed"

[scrolling]
multiplier = 6

[font]
size = 8.5

[font.normal]
family = "Departure Mono"
style = "Regular"

[font.glyph_offset]
x = -1
y = 0

[cursor]
unfocused_hollow = false

[cursor.style]
shape = "Beam"
blinking = "Always"

[mouse]
hide_when_typing = true

